# Generated by Django 4.2.4 on 2023-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_is_spam_globaldb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globaldb",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
