# Generated by Django 4.2.4 on 2023-12-15 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_globaldb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globaldb",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
